<a href="https://colab.research.google.com/github/juanjosedelgado-coder/Talleres/blob/main/Taller_Regresion_Polinomica_Vargas_Cuaspud_Delgado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/LinaMariaCastro/curso-ia-para-economia/blob/main/clases/5_Aprendizaje_supervisado/2_Taller_Regresion_Polinomica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Inteligencia Artificial con Aplicaciones en Economía I**

- 👩‍🏫 **Profesora:** [Lina María Castro](https://www.linkedin.com/in/lina-maria-castro)  
- 📧 **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- 🎓 **Universidad:** Universidad Externado de Colombia - Facultad de Economía

# **Taller: Regresión Polinómica, Subajuste, Sobreajuste y Regularización**

**IMPORTANTE**: Guarda una copia de este notebook en tu Google Drive o computador.

**Taller en grupos de 3**

**Nombres estudiantes:**

- Natalia Vargas
- Marleny Cuaspud
- Juan Jose Delgado

**Forma de entrega:**

- Nombrar el archivo de la siguiente forma: “Taller_Reg_Pol_apellidos.ipynb”.
- Suba el Jupyter Notebook a su cuenta en Github y envíe el link en el siguiente Forms: https://forms.cloud.microsoft/r/AUmhqMjhUK.

**IMPORTANTE:** No se recibirán talleres en Google Colab, el notebook debe estar subido en Github.

**Plazo de entrega:**

30 de abril de 2026, máximo a las 11:59 p.m. Tenga en cuenta que luego de esa hora el formulario en forms se cierra. El Jupupyter Notebook también debe quedar subido en Github antes de esa hora.

**Instrucciones Generales:**

Completa el código en las celdas marcadas con `### TU CÓDIGO AQUÍ ###`. Puedes añadir más celdas si lo requieres.

## **Situación**

Una importante firma de inversión inmobiliaria te ha contratado como consultor de ciencia de datos. Su proceso actual de valoración de propiedades es lento y se basa en la intuición de unos pocos expertos. Quieren que desarrolles un modelo de machine learning para predecir el precio de venta de las viviendas (`SalePrice`) de forma más precisa y sistemática.

Te han entregado el dataset "Ames Housing", que contiene una gran cantidad de información sobre viviendas vendidas recientemente. Tu tarea es construir el mejor modelo posible, pero más importante aún, justificar por qué tu modelo es robusto y fiable, explicando cómo has manejado la complejidad y el riesgo de sobreajuste.

### **Ejercicio 1: Carga y Preparación Inicial de los Datos**

Primero, carguemos las librerías necesarias y el dataset. Nos enfocaremos en un subconjunto de las variables numéricas para mantener el taller manejable, pero el principio se aplica a todo el dataset.

In [30]:
# Importa las librerías necesarias
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Importación de herramientas de scikit-learn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error

Mejorar visualización de dataframes y gráficos

In [31]:
# Que muestre todas las columnas
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

# Configuraciones para una mejor visualización
sns.set(style='whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)

Cargar el dataset

In [32]:
# Usamos el dataset Ames Housing desde su fuente original (requiere internet)
url = 'http://jse.amstat.org/v19n3/decock/AmesHousing.txt'
df = pd.read_csv(url, sep='\t')
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.00,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.00,TA,TA,CBlock,TA,Gd,Gd,BLQ,639.00,Unf,0.00,441.00,"1,080.00",GasA,Fa,Y,SBrkr,1656,0,0,1656,1.00,0.00,1,0,3,1,TA,7,Typ,2,Gd,Attchd,"1,960.00",Fin,2.00,528.00,TA,TA,P,210,62,0,0,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.00,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,NaN,0.00,TA,TA,CBlock,TA,TA,No,Rec,468.00,LwQ,144.00,270.00,882.00,GasA,TA,Y,SBrkr,896,0,0,896,0.00,0.00,1,0,2,1,TA,5,Typ,0,NaN,Attchd,"1,961.00",Unf,1.00,730.00,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.00,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.00,TA,TA,CBlock,TA,TA,No,ALQ,923.00,Unf,0.00,406.00,"1,329.00",GasA,TA,Y,SBrkr,1329,0,0,1329,0.00,0.00,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,"1,958.00",Unf,1.00,312.00,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.00,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,NaN,0.00,Gd,TA,CBlock,TA,TA,No,ALQ,"1,065.00",Unf,0.00,"1,045.00","2,110.00",GasA,Ex,Y,SBrkr,2110,0,0,2110,1.00,0.00,2,1,3,1,Ex,8,Typ,2,TA,Attchd,"1,968.00",Fin,2.00,522.00,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.00,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,NaN,0.00,TA,TA,PConc,Gd,TA,No,GLQ,791.00,Unf,0.00,137.00,928.00,GasA,Gd,Y,SBrkr,928,701,0,1629,0.00,0.00,2,1,3,1,TA,6,Typ,1,TA,Attchd,"1,997.00",Fin,2.00,482.00,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [33]:
# Para este taller, solo usaremos algunas columnas clave para simplificar.
df_sub = df[['Overall Qual', 'Gr Liv Area', 'SalePrice']].copy()
df_sub.columns = ['OverallQual', 'GrLivArea', 'SalePrice'] # Renombrar para facilidad
df_sub.head()

   OverallQual  GrLivArea  SalePrice
0            6       1656     215000
1            5        896     105000
2            6       1329     172000
3            7       2110     244000
4            5       1629     189900

**Explicación de las variables del dataset reducido**

1. SalePrice: Precio de Venta.

Esta es la variable objetivo. Es el precio final por el cual se vendió la propiedad, medido en dólares estadounidenses.

2. OverallQual: Calidad General.

Es una variable ordinal que califica la calidad general del material y el acabado de la casa. Es una de las variables predictoras (X) más importantes.

Escala: Va de 1 a 10.

10: Muy Excelente

9: Excelente

...

2: Pobre

1: Muy Pobre

3. GrLivArea: Área Habitable sobre el Nivel del Suelo.

Es una variable numérica que mide el total de metros cuadrados de área habitable que está por encima del nivel del suelo. No incluye el área del sótano. Es una de las variables predictoras (X) más fuertes, ya que, lógicamente, casas más grandes tienden a ser más caras.

In [34]:
df_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OverallQual  2930 non-null   int64
 1   GrLivArea    2930 non-null   int64
 2   SalePrice    2930 non-null   int64
dtypes: int64(3)
memory usage: 68.8 KB

### **Ejercicio 2: Dividir el conjunto de datos**

El método `.info()` muestra que no hay nulos en nuestro subconjunto. ¡Perfecto! Ahora, definamos nuestras variables `X` (predictoras) e `y` (objetivo) y dividamos los datos.

In [35]:
# Definir X e y
x = df_sub[['OverallQual', 'GrLivArea']] #X (variables predictorias)
y = df_sub['SalePrice'] #Y (Variable objetivo)

In [36]:
# Dividir en entrenamiento y prueba (70/30)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

print(f"Tamaño del set de Entrenamiento: {x_train.shape[0]} observaciones")
print(f"Tamaño del set de Prueba: {x_test.shape[0]} observaciones")

Tamaño del set de Entrenamiento: 2051 observaciones
Tamaño del set de Prueba: 879 observaciones

### **Ejercicio 3: Modelo con Sobreajuste**

Vamos a crear un modelo muy complejo para ver qué tan mal puede generalizar.

**Crear un Modelo Polinómico de Grado 5**

Usa `Pipeline` para combinar `PolynomialFeatures` (grado 5), `StandardScaler` y `LinearRegression`. Entrénalo con los datos de entrenamiento.

In [37]:
# Crear el pipeline para el modelo polinómico
modelo_poly = Pipeline([
    ('poly_features', PolynomialFeatures(degree=5)),
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])

In [38]:
# Entrenar el modelo
modelo_poly.fit(x_train, y_train)

Pipeline(steps=[('poly_features', PolynomialFeatures(degree=5)),
                ('scaler', StandardScaler()), ('model', LinearRegression())])

In [39]:
# Calcular el error (RMSE) en entrenamiento y prueba y realizar un print de estos
#hacemos las predicciones
y_train_pred = modelo_poly.predict(x_train)
y_test_pred = modelo_poly.predict(x_test)
#Ahora calculamos el error (RMSE)
rmse_train_poly = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_poly = np.sqrt(mean_squared_error(y_test, y_test_pred))

print(f"RMSE en Entrenamiento: {rmse_train_poly}")
print(f"RMSE en Prueba: {rmse_test_poly}")

RMSE en Entrenamiento: 34152.34945885959
RMSE en Prueba: 41101.60272605053

**Pregunta:** ¿Qué indica la diferencia que observas entre el error de entrenamiento y el de prueba? ¿Le recomendarías este modelo a la firma inmobiliaria? ¿Por qué?

**R/** El RMSE en entrenamiento es menor que en prueba, lo que indica la presencia de cierto sobreajuste. Sin embargo, la diferencia entre ambos no es excesiva, lo que sugiere que el modelo aún tiene una capacidad razonable de generalización. Aun así, se podría mejorar utilizando técnicas como regularización para reducir el error en datos de prueba.

### **Ejercicio 4: Aplicar Regularización**

Ahora, vamos a "curar" el sobreajuste. Usaremos los mismos `PolynomialFeatures` de grado 5, pero cambiaremos el modelo de regresión.

**Implementar Regresión Ridge**

Copia el pipeline anterior, pero reemplaza `LinearRegression` con `Ridge(alpha=10)`. `alpha` es la fuerza de la penalización.

In [40]:
# Crear el pipeline para Ridge
pipeline_ridge = Pipeline([
    ('poly_features', PolynomialFeatures(degree=5)),
    ('scaler', StandardScaler()),
    ('model', Ridge(alpha=10))
])

In [41]:
# Entrenar el modelo
pipeline_ridge.fit(x_train, y_train)

Pipeline(steps=[('poly_features', PolynomialFeatures(degree=5)),
                ('scaler', StandardScaler()), ('model', Ridge(alpha=10))])

In [42]:
# Calcular el error (RMSE) en entrenamiento y prueba y realizar un print de estos
y_train_pred = pipeline_ridge.predict(x_train)
y_test_pred = pipeline_ridge.predict(x_test)
#Ahora calculamos el error (RMSE)
rmse_train_ridge = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_ridge = np.sqrt(mean_squared_error(y_test, y_test_pred))

print(f"RMSE en Entrenamiento: {rmse_train_ridge}")
print(f"RMSE en Prueba: {rmse_test_ridge}")

RMSE en Entrenamiento: 35204.890355599244
RMSE en Prueba: 35206.62953693654

**Interpreta los resultados:**

**R/** El modelo Ridge reduce significativamente el sobreajuste, ya que los errores de entrenamiento y prueba son prácticamente iguales. Aunque el error en entrenamiento aumenta ligeramente en comparación con el modelo polinómico, el error en prueba disminuye considerablemente, lo que indica una mejor capacidad de generalización. Por esta razón, el modelo Ridge sería más recomendable para una firma inmobiliaria,en vez del modelo polinomico, ya que ofrece predicciones más estables y confiables.

**Implementar Regresión Lasso**

Haz lo mismo, pero ahora con `Lasso(alpha=500, max_iter=10000)`. Lasso necesita un `alpha` más grande (porque la penalización L1 es diferente) y a veces más `max_iter` para converger.

In [43]:
# Crear el pipeline para Lasso
pipeline_lasso = Pipeline([
    ('poly_features', PolynomialFeatures(degree=5)),
    ('scaler', StandardScaler()),
    ('model', Lasso(alpha=500, max_iter=10000))
])

In [44]:
# Entrenar el modelo
pipeline_lasso.fit(x_train, y_train)

Pipeline(steps=[('poly_features', PolynomialFeatures(degree=5)),
                ('scaler', StandardScaler()),
                ('model', Lasso(alpha=500, max_iter=10000))])

In [45]:
# Calcular el error (RMSE) en entrenamiento y prueba y realizar un print de estos
y_train_pred = pipeline_lasso.predict(x_train)
y_test_pred = pipeline_lasso.predict(x_test)
#Ahora calculamos el error (RMSE)
rmse_train_lasso = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_lasso = np.sqrt(mean_squared_error(y_test, y_test_pred))

print(f"RMSE en Entrenamiento: {rmse_train_lasso}")
print(f"RMSE en Prueba: {rmse_test_lasso}")

RMSE en Entrenamiento: 35352.92442589407
RMSE en Prueba: 35447.713244867184

**Interpreta los resultados:**

**R/** El modelo Lasso presenta errores de entrenamiento y prueba muy similares, lo que indica que no hay sobreajuste y que el modelo generaliza bien. Además, permite eliminar variables poco relevantes al llevar sus coeficientes a cero, haciendo el modelo más simple e interpretable. Aunque su precisión es ligeramente menor que la de Ridge, sigue siendo un modelo eficiente y útil para el análisis.

**Selección de Variables con Lasso**

Una de las grandes ventajas de Lasso es que puede eliminar variables. Vamos a ver cuántas de las características polinómicas que creamos (ej. `OverallQual^2`, `GrLivArea^5`, `OverallQual * GrLivArea^4`, etc.) fueron eliminadas.

In [46]:
# Extraer los coeficientes del modelo Lasso
coeficientes = pipeline_lasso.named_steps['model'].coef_
coeficientes

array([     0.        ,   1963.76821109,      0.        ,      0.        ,
        35444.97862341,      0.        ,      0.        ,  10560.00802868,
            0.        ,      0.        ,      0.        ,  21555.1038162 ,
            0.        ,      0.        ,     -0.        ,   9492.34283088,
            0.        ,      0.        ,     -0.        ,     -0.        ,
       -20625.70275837])

In [47]:
# Extraer los nombres de las características generadas
# Guíate por el siguiente código: feature_names = pipeline_lasso.named_steps['poly_features'].get_feature_names_out(X.columns)
feature_names = pipeline_lasso.named_steps['poly_features'].get_feature_names_out(x_train.columns)
feature_names

array(['1', 'OverallQual', 'GrLivArea', 'OverallQual^2',
       'OverallQual GrLivArea', 'GrLivArea^2', 'OverallQual^3',
       'OverallQual^2 GrLivArea', 'OverallQual GrLivArea^2',
       'GrLivArea^3', 'OverallQual^4', 'OverallQual^3 GrLivArea',
       'OverallQual^2 GrLivArea^2', 'OverallQual GrLivArea^3',
       'GrLivArea^4', 'OverallQual^5', 'OverallQual^4 GrLivArea',
       'OverallQual^3 GrLivArea^2', 'OverallQual^2 GrLivArea^3',
       'OverallQual GrLivArea^4', 'GrLivArea^5'], dtype=object)

In [48]:
# Contar cuántos coeficientes son exactamente cero
num_coeficientes_cero = np.sum(coeficientes == 0)
num_coeficientes_cero

np.int64(15)

In [49]:
# Realizar un print de:
# Número total de características polinómicas generadas
# Número de características eliminadas por Lasso (coef = 0)
# Número de características CONSERVADAS
# Porcentaje de variables eliminadas
# Lista con los nombres de las características conservadas por Lasso (coef != 0)
variables_conservadas = feature_names[coeficientes != 0]
variables_conservadas

array(['OverallQual', 'OverallQual GrLivArea', 'OverallQual^2 GrLivArea',
       'OverallQual^3 GrLivArea', 'OverallQual^5', 'GrLivArea^5'],
      dtype=object)

In [50]:
print("Número total de variables:", len(feature_names))
print("Variables eliminadas (coef = 0):", num_coeficientes_cero)
print("Variables conservadas:", len(variables_conservadas))
print("Porcentaje eliminadas:", (num_coeficientes_cero / len(feature_names)) * 100)

print("\nVariables conservadas por Lasso:")
print(variables_conservadas)

Número total de variables: 21
Variables eliminadas (coef = 0): 15
Variables conservadas: 6
Porcentaje eliminadas: 71.42857142857143

Variables conservadas por Lasso:
['OverallQual' 'OverallQual GrLivArea' 'OverallQual^2 GrLivArea'
 'OverallQual^3 GrLivArea' 'OverallQual^5' 'GrLivArea^5']

**Interpreta los resultados:**

**R/** El modelo Lasso no solo reduce el sobreajuste, sino que también realiza selección de variables al llevar algunos coeficientes a cero. Esto permite identificar qué variables polinómicas son realmente relevantes para explicar el precio de la vivienda. Como resultado, el modelo se vuelve más interpretable y eficiente, eliminando características innecesarias.
Esto es especialmente útil en contextos económicos, donde modelos más simples y explicativos son preferibles para la toma de decisiones.

### **Ejercicio 5: Conclusión y Recomendación para el Cliente**

**Resumir los Resultados**

Crea un `DataFrame` de pandas que compare el RMSE de entrenamiento y prueba de los tres modelos (Polinómico, Ridge, Lasso) y ordena los modelos según el RMSE de prueba de menor a mayor.

In [51]:
# Crear DataFrame de resultados
resultados = pd.DataFrame({
    'Modelo': ['Polinómico', 'Ridge', 'Lasso'],
    'RMSE_Train': [rmse_train_poly, rmse_train_ridge, rmse_train_lasso],
    'RMSE_Test': [rmse_test_poly, rmse_test_ridge, rmse_test_lasso]
})

#ordenamos por desempelo en prueba
resultados = resultados.sort_values(by='RMSE_Test')

# Mostrar el DataFrame
resultados

       Modelo  RMSE_Train  RMSE_Test
1       Ridge   35,204.89  35,206.63
2       Lasso   35,352.92  35,447.71
0  Polinómico   34,152.35  41,101.60

**Pregunta Final:**

Basado en tu análisis, ¿qué modelo le recomendarías a la firma inmobiliaria? Tu respuesta debe incluir:

1.  Una recomendación clara del mejor modelo.

**R/**

El modelo recomendado es Ridge, ya que presenta el menor error en los datos de prueba, lo que indica una mejor capacidad predictiva y mayor confiabilidad en escenarios reales.

2.  Una explicación en términos sencillos (para un gerente, no para un científico de datos) de por qué el modelo polinómico simple no era una buena idea, usando el concepto de "memorizar vs. generalizar".

**R/**

El modelo polinómico de alto grado no es una buena opción porque tiende a “memorizar” los datos de entrenamiento en lugar de aprender patrones generales. Esto significa que funciona muy bien con los datos que ya conoce, pero falla al predecir nuevos casos. En cambio, modelos como Ridge logran un mejor equilibrio, permitiendo generalizar mejor a datos no observados.


3.  Una descripción de la ventaja principal del modelo Lasso en cuanto a la interpretabilidad y la selección de las características más importantes.

**R/**

El modelo Lasso tiene como principal ventaja que puede eliminar variables irrelevantes al llevar sus coeficientes a cero, lo que simplifica el modelo y lo hace más fácil de interpretar. Esto es útil para identificar qué factores son realmente importantes en la determinación del precio de la vivienda.